[Desktop Entry]
Type=Service
X-KDE-ServiceTypes=PhononBackend
MimeType=application/x-annodex;video/quicktime;video/x-quicktime;audio/x-m4a;application/x-quicktimeplayer;video/mkv;video/msvideo;video/x-msvideo;video/x-flic;audio/x-aiff;audio/aiff;audio/x-pn-aiff;audio/x-realaudio;audio/basic;audio/x-basic;audio/x-pn-au;audio/x-8svx;audio/8svx;audio/x-16sv;audio/168sv;image/x-ilbm;image/ilbm;video/x-anim;video/anim;image/png;image/x-png;video/mng;video/x-mng;audio/x-ogg;audio/x-speex+ogg;application/ogg;audio/vnd.rn-realaudio;audio/x-pn-realaudio-plugin;audio/x-real-audio;application/vnd.rn-realmedia;video/mpeg;video/x-mpeg;audio/x-wav;audio/wav;audio/x-pn-wav;audio/x-pn-windows-acm;audio/mpeg2;audio/x-mpeg2;audio/mpeg3;audio/x-mpeg3;audio/mpeg;audio/x-mpeg;audio/x-mpegurl;audio/mp3;audio/x-ape;
X-KDE-Library=phonon_gstreamer
X-KDE-PhononBackendInfo-InterfaceVersion=1
X-KDE-PhononBackendInfo-Version=@PHONON_GST_VERSION@
X-KDE-PhononBackendInfo-Website=http://gstreamer.freedesktop.org/
Icon=phonon-gstreamer
InitialPreference=15

Name=GStreamer
Name[ca]=GStreamer
Name[ca@valencia]=GStreamer
Name[cs]=GStreamer
Name[de]=GStreamer
Name[en_GB]=GStreamer
Name[es]=GStreamer
Name[fi]=GStreamer
Name[fr]=GStreamer
Name[id]=GStreamer
Name[is]=GStreamer
Name[ja]=GStreamer
Name[nb]=GStreamer
Name[nl]=GStreamer
Name[nn]=GStreamer
Name[se]=GStreamer
Name[sk]=GStreamer
Name[sr]=Гстример
Name[sr@ijekavian]=Гстример
Name[sr@ijekavianlatin]=GStreamer
Name[sr@latin]=GStreamer
Name[sv]=Gstreamer
Name[uk]=GStreamer
Name[x-test]=xxGStreamerxx

Comment=Phonon GStreamer backend
Comment[ca]=Dorsal GStreamer del Phonon
Comment[ca@valencia]=Dorsal GStreamer del Phonon
Comment[cs]=Podpůrná vrstva GStreamer pro Phonon
Comment[de]=Phonon-Treiber für GStreamer
Comment[en_GB]=Phonon GStreamer backend
Comment[es]=Motor GStreamer para Phonon
Comment[fi]=Phonon GStreamer -taustajärjestelmä
Comment[fr]=Moteur GStreamer pour Phonon 
Comment[id]=Phonon GStreamer backend
Comment[is]=Phonon GStreamer bakendi
Comment[ja]=Phonon GStreamer バックエンド
Comment[nb]=Phonon-motor for GStreamer
Comment[nl]=GStreamer-backend (Phonon)
Comment[nn]=Phonon-motor for GStreamer
Comment[se]=Phonon GStreamer duogášmohtor
Comment[sk]=Podsystém Phonon GStreamer
Comment[sr]=Гстример као позадина Фонона
Comment[sr@ijekavian]=Гстример као позадина Фонона
Comment[sr@ijekavianlatin]=GStreamer kao pozadina Phonona
Comment[sr@latin]=GStreamer kao pozadina Phonona
Comment[sv]=Phonon Gstreamer-gränssnitt
Comment[uk]=Модуль використання GStreamer у Phonon
Comment[x-test]=xxPhonon GStreamer backendxx
